name: check-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,15 * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-update.yml

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      COMMIT_HASH_FILE: last-commit-hash
      GITHUB_REPO_URL: https://github.com/NationalSecurityAgency/ghidra/

    steps:
      - uses: actions/checkout@v3
      
      - name: Update to latest hash
        run: |
          git config --global user.email "13070+topia@users.noreply.github.com"
          git config --global user.name "Tatsuya Noda"
          commit="$(git ls-remote ${GITHUB_REPO_URL%/}.git HEAD | cut -f1)"
          echo "$commit" > "$COMMIT_HASH_FILE"
          git add "$COMMIT_HASH_FILE"
          if git commit -m "update to $commit: ${GITHUB_REPO_URL%/}/tree/$commit"; then
            git push origin HEAD
          fi
