# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Update to latest hash
        run: |
          git config --global user.email "13070+topia@users.noreply.github.com"
          git config --global user.name "Tatsuya Noda"
          commit="$(git ls-remote https://github.com/NationalSecurityAgency/ghidra.git HEAD | cut -f1)"
          COMMIT_HASH_FILE=last-commit-hash
          echo "$commit" > "$COMMIT_HASH_FILE"
          git add "$COMMIT_HASH_FILE"
          git commit -m "update to $commit: https://github.com/NationalSecurityAgency/ghidra/tree/$commit"
          git push origin HEAD
