# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Update to latest hash
        run: |
          git config --global user.email "13070+topia@users.noreply.github.com"
          git config --global user.name "Tatsuya Noda"
          commit="$(git ls-remote https://github.com/NationalSecurityAgency/ghidra.git HEAD | cut -f1)"
          COMMIT_HASH_FILE=last-commit-hash
          echo "$commit" > "$COMMIT_HASH_FILE"
          git add "$COMMIT_HASH_FILE"
          if git commit -m "update to $commit: https://github.com/NationalSecurityAgency/ghidra/tree/$commit"; then
            git push origin HEAD
          fi

      - name: Add tag
        run: |
          TAG_NAME="snapshot-$(date +%Y-%m-%d-%H)"
          git tag -a "$TAG_NAME" -m "tag to build $commit: https://github.com/NationalSecurityAgency/ghidra/tree/$commit"
          git push origin "$TAG_NAME"
